### ISSUE TITLE
pgcli does not say anything on syntax error when table_format is csv

### ISSUE THREAD

**Issue by autra** [dbcli/pgcli#1337] opened 2022-05-10 13:53 UTC
## Description

If table_format is set to csv, when making any kind of sql syntax error, pgcli just doesn't say anything. Example:

```
psql://atr@localhost/tethys> test;
Time: 0.017s
```

## Your environment

- [x] Please provide your OS and version information: kubuntu 20.04
- [x] Please provide your CLI version: 3.4.1

**Comment by lelit** [comment] 2022-05-10 14:42
Likely a duplicate of issue #1200

**Comment by j-bennet** [comment] 2022-09-03 00:05
Closed as duplicate of https://github.com/dbcli/pgcli/issues/1200.

**Closed by j-bennet** 2022-09-03 00:05 UTC
