### ISSUE TITLE
\watch command does not work

### ISSUE THREAD

**Issue by gabfl** [dbcli/pgcli#544] opened 2016-07-06 16:03 UTC
(this is a minor issue as `\watch` is not a well known command)

PostgreSQL has a `\watch` command to repeat queries every X seconds (as documented here): https://www.postgresql.org/docs/current/static/app-psql.html

It works perfectly on the psql CLI:

``` sql
gab@db > SELECT 1; \watch 1;
 ?column? 
----------
        1
(1 row)

Time: 0.187 ms
Watch every 1s  Wed Jul  6 12:01:54 2016

 ?column? 
----------
        1
(1 row)

Time: 0.047 ms
Watch every 1s  Wed Jul  6 12:01:55 2016

 ?column? 
----------
        1
(1 row)

Time: 0.154 ms
Watch every 1s  Wed Jul  6 12:01:56 2016

 ?column? 
----------
        1
(1 row)

Time: 0.164 ms
```

It does not work with pgcli:

``` sql
db> SELECT 1; \watch 1;
+------------+
|   ?column? |
|------------|
|          1 |
+------------+
SELECT 1
syntax error at or near "\"
LINE 1: \watch 1
        ^

Time: 0.003s
```

**Comment by amjith** [comment] 2016-07-17 04:24
This has not been implemented yet. But this is something we want to support.

**Comment by gabfl** [comment] 2016-07-17 14:08
great, thanks Amjith!

**Comment by amjith** [comment] 2016-09-03 03:27
Please upgrade to v1.2.0. 

```
pip install -U pgcli
```

This issue is addressed in the new version.

**Comment by gabfl** [comment] 2016-09-06 14:41
Just tested and it works great, thank you so much

**Comment by levin-kelevra** [comment] 2017-04-18 05:10
Version: 1.5.1
Doesn't work.
ОШИБКА:  ошибка синтаксиса (примерное положение: "/")
LINE 1: /watch 1

ERROR: Syntax error

**Comment by amjith** [comment] 2017-04-20 14:04
@j-bennet Can you take a look at this? I don't have a working postgres on my new computer to debug this.

**Comment by j-bennet** [comment] 2017-04-20 15:14
@levin-kelevra Were you entering `/watch` or `\watch`? The error seems to suggest that it was a forward slash. It should be a backslash.

**Comment by j-bennet** [comment] 2017-04-25 23:00
I'm going to leave the issue closed since there's been no update. @levin-kelevra, feel free to reopen if you're still having problems.

**Comment by ivyleavedtoadflax** [comment] 2017-05-09 10:07
This also does not work for me in 1.5.1 on OSX:

```
select * from users where id >12;\watch 1;
...
SELECT 2
syntax error at or near "\"
LINE 1: \watch 1
        ^
```

**Comment by j-bennet** [comment] 2017-05-11 17:23
@ivyleavedtoadflax Now I got it. This happens when you don't have a space after the semicolon:

```
select * from users where id >12;\watch 1;
```

This will work:

```
select * from users where id >12; \watch 1;
```

Yes, it's a valid bug, because both versions should work. Thanks for the report.

**Comment by ivyleavedtoadflax** [comment] 2017-05-17 12:34
This also fails when `\watch` is on a new line from a query loaded with `\i`. e.g.:

```
select * from users;
\watch 1;
```

**Comment by j-bennet** [comment] 2017-06-09 16:05
Fixed in pgspecial 1.8.0.

**Comment by fake-name** [comment] 2018-01-15 06:43
This is *not* fixed.

```
durr@postgres-server /e/a/apt.conf.d> sudo -H -u postgres pgcli
Version: 1.8.2
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres> \timing
postgres> select * from pg_stat_progress_vacuum;
+-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
| pid   | datid   | datname    | relid    | phase          | heap_blks_total   | heap_blks_scanned   | heap_blks_vacuumed   | index_vacuum_count   | max_dead_tuples   | num_dead_tuples   |
|-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------|
| 7364  | 16412   | webarchive | 38269410 | vacuuming heap | 9302840           | 9302840             | 5240289              | 1                    | 178956970         | 25702032          |
| 5029  | 16412   | webarchive | 38269400 | scanning heap  | 12280964          | 2858029             | 0                    | 0                    | 178956970         | 16892993          |
+-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
SELECT 2
Time: 0.010s
postgres> \watch
syntax error at or near "\"
LINE 1: \watch
        ^
```

**Comment by fake-name** [comment] 2018-01-15 06:48
Oh, I see, it's just it's interface is different:

```
postgres> select * from pg_stat_progress_vacuum;
+-------+---------+------------+-----------+-------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
| pid   | datid   | datname    | relid     | phase             | heap_blks_total   | heap_blks_scanned   | heap_blks_vacuumed   | index_vacuum_count   | max_dead_tuples   | num_dead_tuples   |
|-------+---------+------------+-----------+-------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------|
| 7364  | 16412   | webarchive | 38269410  | vacuuming heap    | 9302840           | 9302840             | 5261471              | 1                    | 178956970         | 25702032          |
| 5029  | 16412   | webarchive | 38269400  | scanning heap     | 12280964          | 2967063             | 0                    | 0                    | 178956970         | 16943994          |
| 11173 | 16411   | ttrss      | 230002899 | vacuuming indexes | 21                | 21                  | 0                    | 0                    | 6111              | 638               |
+-------+---------+------------+-----------+-------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
SELECT 3
Time: 0.005s
postgres> \watch 1
syntax error at or near "\"
LINE 1: \watch 1
        ^

Time: 0.002s
postgres> select * from pg_stat_progress_vacuum; \watch
+-------+---------+------------+-----------+---------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
| pid   | datid   | datname    | relid     | phase               | heap_blks_total   | heap_blks_scanned   | heap_blks_vacuumed   | index_vacuum_count   | max_dead_tuples   | num_dead_tuples   |
|-------+---------+------------+-----------+---------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------|
| 7364  | 16412   | webarchive | 38269410  | vacuuming heap      | 9302840           | 9302840             | 5262691              | 1                    | 178956970         | 25702032          |
| 5029  | 16412   | webarchive | 38269400  | scanning heap       | 12280964          | 2973478             | 0                    | 0                    | 178956970         | 16947189          |
| 11173 | 16411   | ttrss      | 230002905 | cleaning up indexes | 3547              | 3547                | 3547                 | 0                    | 1032177           | 0                 |
+-------+---------+------------+-----------+---------------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
SELECT 3
syntax error at or near "\"
LINE 1: \watch
        ^

Time: 0.007s
postgres> select * from pg_stat_progress_vacuum; \watch 1
+-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
| pid   | datid   | datname    | relid    | phase          | heap_blks_total   | heap_blks_scanned   | heap_blks_vacuumed   | index_vacuum_count   | max_dead_tuples   | num_dead_tuples   |
|-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------|
| 7364  | 16412   | webarchive | 38269410 | vacuuming heap | 9302840           | 9302840             | 5263696              | 1                    | 178956970         | 25702032          |
| 5029  | 16412   | webarchive | 38269400 | scanning heap  | 12280964          | 2977029             | 0                    | 0                    | 178956970         | 16953488          |
+-------+---------+------------+----------+----------------+-------------------+---------------------+----------------------+----------------------+-------------------+-------------------+
SELECT 2
Time: 0.005s
Waiting for 1 seconds before repeating
```

So, the issue is then:
 - `\watch 1` as a single statement does not work (in `psql`, `\watch` with no SQL in the command line assumes you want to watch the previously executed query).
 - `\watch` with no argument does not work (`psql` defaults to I think 2 seconds if the interval is not specified).
 - In both cases, the (mis)use of the `\watch` command doesn't lead to any sort of helpful output.
 - `\?` doesn't list the mnemonics of `\watch` at all, so you don't have anything to base how you are *supposed* to use it off of.

**Comment by j-bennet** [comment] 2018-01-15 18:28
Good point. It does work, but the interface is not very user-friendly.

**Comment by fake-name** [comment] 2018-01-15 20:55
I guess the question is more "Is `\watched` supposed to mimic the `psql` `\watch` behaviour exactly (as it seems the other `pgcli` `\` functions do?" 

If `pgcli` is just trying to be feature *similar*, it's certainly there already, just fixing `\?` would suffice. 

If `pgcli` is trying to act like a *better* `psql`, it's definitely not correct yet.

**Comment by antislice** [comment] 2019-08-01 23:07
I also just ran into this not working with a multiline query - e.g.
```
<bunch of sql...>
                         ORDER BY a.query_start; \watch 15;

<result>
SELECT 3
syntax error at or near "\"
LINE 1: \watch 15
```

If it wasn't required to have `\watch` on the same line as the query I'd just use that and move on, but because it is necessary I figured I'd leave a comment. I'm using version 1.10.3 on mac.

**Closed** 2021-09-30 19:00 UTC
