### ISSUE TITLE
Bug: Results sometimes get not shown

### ISSUE THREAD

**Issue by brasilikum** [dbcli/pgcli#791] opened 2017-09-17 20:15 UTC
## Description

<img width="1135" alt="screen shot 2017-09-17 at 15 06 21" src="https://user-images.githubusercontent.com/3106990/30524510-cc7f85e4-9bba-11e7-9708-758d0af7dd70.png">

For some queries (could not narrow it down, other than it seems to happen when the results are less then 1000) results are not shown.

I attached a screenshot (left Postico, right pgcli).

I only experience this since 1.8.0, which gave me really nice "shadow autocomplete", but seemingly also this bug.

I really love pgcli! Thanks to all maintainers and contributors.

## Your environment

- MacOS High Sierra 10.13 Beta
- PGcli 1.8.0
- iTerm2 3.0.15

```
agate==1.6.0
agate-dbf==0.2.0
agate-excel==0.2.1
agate-sql==0.5.2
astroid==1.5.3
Babel==2.4.0
*Confidential repo removed*
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
csvkit==1.0.2
csvtools==0.5.1
dbfread==2.0.7
et-xmlfile==1.0.1
flake8==3.4.1
future==0.16.0
idna==2.5
isodate==0.5.4
isort==4.2.15
jdcal==1.3
lazy-object-proxy==1.3.1
leather==0.3.3
mccabe==0.6.1
openpyxl==2.4.8
parsedatetime==2.4
pycodestyle==2.3.1
pyflakes==1.5.0
pylint==1.7.2
python-dotenv==0.6.4
python-slugify==1.2.4
pytimeparse==1.1.6
pytz==2017.2
requests==2.18.3
six==1.10.0
sparkpost==1.3.5
SQLAlchemy==1.1.13
Unidecode==0.4.21
urllib3==1.22
wrapt==1.10.10
xlrd==1.0.0
```

**Comment by j-bennet** [comment] 2017-09-17 21:13
@meeuw Do you think this may be a result of switching to a generator vs list for displaying results? From this issue it seems like the generator is exhausted somewhere, or reading and swallowing the first few lines.

**Comment by meeuw** [comment] 2017-09-18 08:00
It surely smells like it, but I cannot reproduce this, @brasilikum could you please tell us which version of cli_helpers is installed? We've had this with mycli but that was in the conditional pager support (which isn't in pgcli).

**Comment by brasilikum** [comment] 2017-09-18 13:34
@meeuw How do I do that?
I installed pgcli via brew

**Comment by brasilikum** [comment] 2017-09-18 13:40
@meeuw How do I do that?
I installed pgcli via brew

**Comment by meeuw** [comment] 2017-09-18 18:45
I can reproduce your error by using an older version of cli_helpers. I've updated the dependencies for setup.py and @tsroten is working on getting it updated on homebew.

**Comment by tsroten** [comment] 2017-09-18 18:48
The pull request has been submitted to Homebrew. Once, it's merged, I'll post here.

**Comment by tsroten** [comment] 2017-09-21 11:52
@brasilikum Ok, Homebrew has been updated! You should be able to do:
```bash
brew update
brew upgrade pgcli
```

**Closed** 2017-09-21 11:53 UTC

**Comment by brasilikum** [comment] 2017-09-21 15:35
Can confirm, it works! Thanks
