### ISSUE TITLE
y is not a valid boolean error is displayed sometimes when acknowledging a destructive command

### ISSUE THREAD

**Issue by butla** [dbcli/pgcli#932] opened 2018-08-16 15:16 UTC
## Description
Today I noticed that sometimes when I run "destructive" commands and I answer with "y" I see an error, that still doesn't seem to affect the functionality. It's a bit off-putting, though, especially when I run some important stuff. And example:

```
XXX@Y:ZZZ> alter table bla1 ADD CONSTRAINT bla1_id_unique UNIQUE(id);
               alter table bla2 ADD CONSTRAINT bla2_id_unique UNIQUE(id);
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Error: y is not a valid boolean
```

It seems to not happend when I provide only one command.

## Your environment

- [x] Please provide your OS and version information.
Kubuntu 18.04.1
- [x] Please provide your CLI version.
1.10.3
- [x] What is the output of ``pip freeze`` command.
```
appdirs==1.4.3
apt-xapian-index==0.47
arrow==0.10.0
asciinema==1.4.0
asn1crypto==0.23.0
astroid==1.6.0
attrs==17.3.0
autobahn==17.10.1
Automat==0.6.0
awscli==1.15.45
awslogs==0.10.0
babelfish==0.5.5
backports.csv==1.0.5
beautifulsoup4==4.6.0
binaryornot==0.4.4
boto3==1.7.45
botocore==1.10.45
cached-property==1.3.1
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
cli-helpers==1.0.2
click==6.7
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cookiecutter==1.6.0
credstash==1.14.0
cryptography==2.0.3
cupshelpers==1.0
decorator==4.2.1
distro-info==0.18
docker==3.3.0
docker-compose==1.21.2
docker-pycreds==0.3.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.14
dogpile.cache==0.6.4
entrypoints==0.2.3
enzyme==0.4.1
first==2.0.1
future==0.16.0
greenlet==0.4.12
guessit==2.1.4
hkdf==0.0.3
httpie==0.9.9
httplib2==0.9.2
humanize==0.5.1
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
isort==4.2.15
jedi==0.11.0
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
jsonschema==2.6.0
keyring==13.2.1
keyrings.alt==3.0
lambda-uploader==1.2.0
language-selector==0.1
lazy-object-proxy==1.3.1
magic-wormhole==0.10.3
MarkupSafe==1.0
mccabe==0.6.1
meld==3.18.0
msgpack==0.5.6
neovim==0.2.6
networkx==2.1
olefile==0.45.1
parso==0.1.0
pbr==3.1.1
pexpect==4.2.1
pgcli==1.10.3
pgspecial==1.11.2
Pillow==5.1.0
pip-tools==2.0.2
pipenv==2018.7.1
pkginfo==1.4.2
pluggy==0.6.0
poyo==0.4.1
prompt-toolkit==1.0.15
psycopg2==2.7.5
ptpython==0.41
pudb==2017.1.4
py==1.5.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycparser==2.18
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.26.1
pylint==1.8.1
PyNaCl==1.2.0
pyOpenSSL==17.4.0
Pyro4==4.63
pysrt==1.1.1
python-apt==1.6.2
python-dateutil==2.6.1
python-debian==0.1.32
pytz==2017.3
pyusb==1.0.0
pyxdg==0.25
PyYAML==3.12
rarfile==3.0
rebulk==0.9.0
reportlab==3.4.0
requests==2.18.4
requests-toolbelt==0.8.0
requests-unixsocket==0.1.5
rsa==3.4.2
s3transfer==0.1.13
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
serpent==1.23
service-identity==17.0.0
setproctitle==1.1.10
six==1.11.0
snakeviz==0.4.2
spake2==0.7
sqlparse==0.2.4
stevedore==1.27.1
subliminal==2.0.5
systemd-python==234
tabulate==0.8.2
termcolor==1.1.0
terminaltables==3.1.0
texttable==0.9.1
tornado==4.5.2
tox==3.0.0
tqdm==4.19.4
twine==1.11.0
Twisted==17.9.0
txaio==2.8.2
txtorcon==0.19.3
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.22
urwid==1.3.1
vboxapi==1.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.8.2
virtualfish==1.0.5
wcwidth==0.1.7
websocket-client==0.44.0
whichcraft==0.4.1
wrapt==1.10.11
xkit==0.0.0
xonsh==0.6.0
zope.interface==4.4.3
```

**Comment by dbaty** [comment] 2023-09-27 07:14
I cannot reproduce this issue with the latest version (3.5.0). I suppose that it has been fixed. Shall we close this issue?


<details>
<summary>Repro</summary>

```
pgcli-dev> create table bla1 (id int)
CREATE TABLE
pgcli-dev> create table bla2 (id int)
CREATE TABLE
pgcli-dev> alter table bla1 ADD CONSTRAINT bla1_id_unique UNIQUE(id);
                alter table bla2 ADD CONSTRAINT bla2_id_unique UNIQUE(id);
 
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
ALTER TABLE
ALTER TABLE
pgcli-dev> \d bla1
+--------+---------+-----------+
| Column | Type    | Modifiers |
|--------+---------+-----------|
| id     | integer |           |
+--------+---------+-----------+
Indexes:
    "bla1_id_unique" UNIQUE CONSTRAINT, btree (id)

pgcli-dev> \d bla2
+--------+---------+-----------+
| Column | Type    | Modifiers |
|--------+---------+-----------|
| id     | integer |           |
+--------+---------+-----------+
Indexes:
    "bla2_id_unique" UNIQUE CONSTRAINT, btree (id)

```
</details>

**Comment by j-bennet** [comment] 2023-09-27 18:40
Closed as completed.

**Closed by j-bennet** 2023-09-27 18:40 UTC
Labels: easy
