### ISSUE TITLE
Error while trying to run pgcli

### ISSUE THREAD

**Issue by kornelijussl** [dbcli/pgcli#1290] opened 2021-10-12 05:21 UTC
## Description

Hello, I'm having a hard time installing and running pgcli. Installation with command pip install pgcli seemed to be successful but trying to launch the utility I'm getting this error: 

>  from psycopg2._psycopg import (                     # noqa
ImportError: DLL load failed while importing _psycopg: The specified module could not be found.

## Your environment

- [x] Please provide your OS and version information. : Windows 10.
- [x] Please provide your CLI version. 
- [x] What is the output of ``pip freeze`` command. : 

- cli-helpers==2.2.0
- click==8.0.3
- colorama==0.4.4
- configobj==5.0.6
- pendulum==2.1.2
- pgcli==3.2.0
- pgspecial==1.13.0
- prompt-toolkit==3.0.20
- psycopg2==2.9.1
- psycopg2-binary==2.9.1
- Pygments==2.10.0
- python-dateutil==2.8.2
- pytzdata==2020.1
- setproctitle==1.2.2
- six==1.16.0
- sqlparse==0.4.2
- tabulate==0.8.9
- wcwidth==0.2.5

**Comment by laixintao** [comment] 2021-12-05 07:47
Hi sorry about your pain.

I think it is because your `psycopg2-binary` not installed correctly.

can you try this import on your python shell (which is the one you use to start pgcli), like this:

```
$ python
Python 3.7.5 (default, Sep  2 2021, 16:30:33)
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>>
```

Once you do this without any errors (like mine), I think pgcli will work fine.

other wise you need to bugshooting for your psycopg2 installation.

**Comment by dbaty** [comment] 2023-11-15 19:31
No news for 2 years. Let's hope that the report found out the cause of the error. I am hence closing this issue.

**Closed by dbaty** 2023-11-15 19:31 UTC
