### ISSUE TITLE
Autosuggest doesn't work for table "match"

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#401] opened 2015-10-27 16:22 UTC
Run:

```
create table match(hai text);
select * from match m;
```

Now replace `*` with `m.<tab>`. Nothing will happen. Repeat "match2" to see that pgcli doesn't think it's a keyword anymore.

**Comment by darikg** [comment] 2015-10-27 16:51
As a workaround you can escape the tablename like `select m.<tab> from "match" m`

The problem is that `match` is a [keyword ](http://www.postgresql.org/docs/9.2/static/sql-keywords-appendix.html). Currently `parse_utils.extract_tables` [stops](https://github.com/dbcli/pgcli/blob/a5cf7d9ba273854d9ad5dfba8a3d3a57ded651fe/pgcli/packages/parseutils.py#L101) once it hits a `Keyword`. We could do a lot better if we had a way of distinguishing between reserved and non-reserved keywords.

**Comment by j-bennet** [comment] 2019-05-05 15:16
Escaping keywords with quotes is a fair solution. Closing.

**Closed by j-bennet** 2019-05-05 15:16 UTC
