### ISSUE TITLE
Feature suggestion: Auto-capitalization of key words

### ISSUE THREAD

**Issue by danielyli** [dbcli/pgcli#615] opened 2016-11-21 22:42 UTC
I find SQL keywords in all caps to be easier to read than when lowercased (even with pgcli's syntax coloring).  Would it be difficult to add an auto-capitalization feature, so that when `select ` is typed, it's replaced with `SELECT `?

**Comment by j-bennet** [comment] 2016-11-21 22:56
There are config settings for that already:

https://github.com/dbcli/pgcli/blob/9584c82a354c5ef6fe94080447c5f506a3376c16/pgcli/pgclirc#L34-L45

**Comment by danielyli** [comment] 2016-11-21 23:03
Oh, wonderful! Thank you.

**Comment by amjith** [comment] 2016-11-21 23:04
The config file is located at `~/.config/pgcli/config`

**Comment by danielyli** [comment] 2016-11-21 23:08
@amjith Thank you.

**Comment by danielyli** [comment] 2016-11-21 23:17
@j-bennet I've added the lines you referenced into my `~/.config/pgcli/config` file, but pgcli isn't auto-capping keywords.  What am I missing?

**Comment by amjith** [comment] 2016-11-21 23:19
@danielyli This is a new feature that was added recently. Can you try upgrading? 

```
pip install -U pgcli
```

**Comment by danielyli** [comment] 2016-11-21 23:23
I'm using Homebrew to manage my packages, and it still has pgcli at 1.1.0.  Who normally updates the Homebrew formulas?  Can we ask her to update?

**Comment by j-bennet** [comment] 2016-11-21 23:46
@amjith did it before, but I'll see if I can help out.

**Comment by danielyli** [comment] 2016-11-22 00:15
@j-bennet Thank you!

**Comment by danielyli** [comment] 2016-11-22 00:16
@j-bennet I took a look at the formula myself to see if I could update it.  I don't know the library dependencies well enough to do it with any assurance that I won't break anything.

Thank you!

**Comment by j-bennet** [comment] 2016-11-22 01:05
For myself and others, instructions from @amjith (awesome as always) about how to create that formula:

> 
> Create a new virtualenv. Let's call it `poet`. 
> 
> Now install mycli inside the `poet` virtualenv. Then install this python package: https://pypi.python.org/pypi/homebrew-pypi-poet. 
> 
> Run: 
> 
> ```
> poet -r mycli > mycli_snippet
> ```
> 
> This will generate the necessary snippet for the formula and write it to the `mycli_snippet` file. 
> 
> Now fork the homebrew repo: https://github.com/Homebrew/homebrew-core and clone it locally. 
> 
> Edit the mycli formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mycli.rb
> 
> Copy the resource stanzas in the formula from the generated snippet.
> 
> You'll see that mycli is listed in the generated snippet, you'll have to move that to these lines: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mycli.rb#L4-L5
> 
> Then you're all done.
> 
> Make a commit. They have some suggestions about the commit message. It should be "mycli 1.8.0".
> 
> Then submit a PR. 
>

**Comment by j-bennet** [comment] 2016-11-22 20:26
Opened a PR in homebrew-core to update pgcli to 1.3.1:

https://github.com/Homebrew/homebrew-core/pull/7163

**Comment by j-bennet** [comment] 2016-11-22 22:49
Homebrew PR was merged, pgcli 1.3.1 now available.

**Comment by danielyli** [comment] 2016-11-22 23:51
@j-bennet Thank you!!

I'm using v1.3.1 now with the `keyword_casing = upper` setting, but that only affects the casing of tab-completed keywords, not regularly typed words.  I must not have been clear from the start; my apologies.  Let me explain what I originally suggested as a feature:

In the pgcli prompt, it would be great to have pgcli automatically correct the casing of keywords, without having to use the tab completion menu.  For example, I would type `s` `e` `l` `e` `c` `t`, all in lowercase, and when I hit `(space)`, pgcli recognizes that word as a keyword and capitalizes it.

Currently, to do something like this, I'd have to watch the tab-completion menu, hit `(tab)` to complete, and then `(space)`.

**Comment by j-bennet** [comment] 2016-11-23 00:37
Hmm, I see. Not sure how feasible this is, but reopened the issue to look again later.

**Comment by amjith** [comment] 2016-11-23 05:52
> For example, I would type s e l e c t, all in lowercase, and when I hit (space), pgcli recognizes that word as a keyword and capitalizes it.

@danielyli That is a dangerous precedent that we'd like to avoid. If a user chooses an entry from the menu by using the up/down arrow or tab key then it is a choice made by the user. But if we go in and modify what the user has typed in, it can lead to undesired behavior. For example, I've seen table named `session` which is a reserved keyword in postgres. If we took this approach of auto-capitalization of keywords then anytime the user types `session` we'll replace it with `SESSION`. This is just one example. 

In general we'd like to avoid changing the query typed by the user. So the closest solution to your request is what we have implemented already.

**Comment by danielyli** [comment] 2016-11-23 06:35
@amjith I thought pgcli knows the context of words typed on the command line?  For example, if I create a table named `session`, I get the following in the auto-complete menu when typing a SELECT statement:

    > select * from session|     <--- the pipe at the end indicates where the cursor is
                            "session"                                 table
                            session_user()                            function
                            pg_replication_origin_session_is_setup()  function
                            pg_replication_origin_session_progress()  function
                            pg_replication_origin_session_reset()     function
                            pg_replication_origin_session_setup()     function
                            pg_stat_reset_single_function_counters()  function
                            pg_stat_reset_single_table_counters()     function

None of the suggestions are of the keyword `SESSION`, and the only correct suggestion, `"session"`, is correctly identified as a table.

**Comment by amjith** [comment] 2016-11-24 06:23
It does know the context for the most part. It works great for nearly 90% of inputs (probably more). But writing auto-completers is hard since we're working with partial statements. So the syntax is not fully formed which makes it hard to compensate for parser shortcomings. I guess what I'm saying is when the sql statement gets complicated it can cause unexpected behavior. 

So we can't rely on the parser to do a good job in discerning a table name vs a keyword. This becomes especially relevant when you start writing nested SQL such as 

```
WITH RECURSIVE search_graph(id, link, data, depth) AS (
        SELECT g.id, g.link, g.data, 1
        FROM graph g
      UNION ALL
        SELECT g.id, g.link, g.data, sg.depth + 1
        FROM graph g, search_graph sg
        WHERE g.id = sg.link
)
SELECT * FROM search_graph;
```

Obviously I'm giving you a worst case scenario but my attempt is to demonstrate why it is undesirable to rewrite a query that a user has typed in with insufficient context.

**Comment by j-bennet** [comment] 2016-11-24 06:34
I think @amjith is right. Currently, it's only pgcli completer that has to know where it is in the query and make intelligent guesses. But even so, the completer leaves the final choice to the user. It can't be 100% sure what user wants at this point in query. The formatter won't have this opportunity for the user to go back and correct the formatting. There's less room to be unsure. We're pretty much certain to have some of the case changing done wrong, and bugs filed.

**Comment by danielyli** [comment] 2016-11-24 07:57
That makes sense.  I can see how such a feature would hurt more than help.  @amjith, thanks for the comprehensive explanation!

**Closed** 2017-03-07 05:20 UTC
