### ISSUE TITLE
resizing pgcli kills the query and connection

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [dbcli/pgcli#1021] opened 2019-03-15 09:39 UTC
## Description

i work with a tiling window manager and every time, a long runnung query is active and i resize the terminal emulator i kill the current query:

    (4, 'Interrupted system call')

and i have to quit pgcli and reconnect

## Your environment

* i3-gaps
* alacritty terminal emulator
* pgcli version 2.0.2

```
$ neofetch
       _,met$$$$$gg.          easteregg@x250
    ,g$$$$$$$$$$$$$$$P.       --------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux buster/sid x86_64
 ,$$P'              `$$$.     Model: 20CM001RGE ThinkPad X250
',$$P       ,ggs.     `$$b:   Kernel: 4.20.14-towo.1-siduction-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 6 days, 1 hour, 4 minutes
 $$P      d$'     ,    $$P    Packages: 3856 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.2
 $$;      Y$b._   _,d$P'      Resolution: 3840x2160, 1920x1080
 Y$$.    `.`"Y$$$$P"'         WM: i3
 `$$b      "-.__              Terminal: alacritty
  `Y$$                        CPU: Intel i7-5600U (4) @ 3.200GHz
   `Y$$.                      GPU: Intel HD Graphics 5500
     `$$b.                    Memory: 5127MiB / 15765MiB
       `Y$$b.
          `"Y$b._
              `"""

```

**Comment by amjith** [comment] 2019-03-15 14:44
That's awful. I just checked it on my machine and I'm able to reproduce it. I'll dig into this one. Sorry about the trouble.

**Comment by verfriemelt-dot-org** [comment] 2019-03-15 15:27
no problem, i tend to give pgcli just its own workspace :D

**Comment by amjith** [comment] 2019-03-16 03:34
This was a tricky problem. But I do have a solution. 

Can you try this branch? 

```
pip install -U https://github.com/dbcli/pgcli/archive/system-error.zip
```

BTW, this is only an issue in Python 2.7, this error does not happen in Python 3.4 and above due to this [PEP](https://www.python.org/dev/peps/pep-0475/).

**Comment by verfriemelt-dot-org** [comment] 2019-03-16 06:07
this works fine!

im not an python expert. the default python seems to be 2.7.16

```
$ python -V
Python 2.7.16
```

how can i switch this version on a per application basis?

**Comment by amjith** [comment] 2019-03-16 21:21
This branch will be merged into master and will be part of the next release. So you don't need to worry about installing it via Python 3. 

Buf if you're generally interested in learning how to install this via Python3. Here's how I'd do it: 

1. Check if python3 is already available for your system. 
`    $ which python3`
2. If it is not available install it. 
`    $ sudo apt-get install python3`
3. Install pip for python3.
`    $ sudo apt-get install python3-pip`
4. Install pgcli using pip3
```
    $ pip uninstall pgcli   # Removes the old version of pgcli installed using python2.7
    $ pip3 install pgcli     # Installs pgcli using python3
```

Tada!

**Closed** 2019-03-17 06:04 UTC

**Comment by verfriemelt-dot-org** [comment] 2019-03-17 08:37
thank you very much with all your efforts and the great responsetime!
