### ISSUE TITLE
set_session cannot be used inside a transaction

### ISSUE THREAD

**Issue by orf** [dbcli/pgcli#646] opened 2017-03-03 10:13 UTC
Just freshly installed `pgcli` and upon trying to connect to my local postgres database I get:

   orf@mean-lean-dev-machine:~|⇒  pgcli -d doge doge -U doge
   set_session cannot be used inside a transaction

Does this mean anything?

**Comment by mafrosis** [comment] 2017-03-03 13:18
Same here too. Cannot connect, only message is the following (which returns nothing on Google search)..

    set_session cannot be used inside a transaction

**Comment by amjith** [comment] 2017-03-03 13:46
I'm able to reproduce it. Looks like it is caused by the latest version of `psycopg2`. I'll try to find out why this is happening, but in the mean time you can install an older version of psycopg2 and continue using pgcli. Here's how you can install an older version of psycopg2. 

```
pip install psycopg2==2.6.2
```

**Comment by mafrosis** [comment] 2017-03-03 14:06
Thanks for quick response @amjith

**Comment by amjith** [comment] 2017-03-03 14:07
I found the issue. I've created a PR #647. We'll get that merged in soon and release a new version. Sorry about the trouble.

**Closed** 2017-03-03 18:26 UTC
Labels: in progress
