### ISSUE TITLE
can't create a connection with the recommend command

### ISSUE THREAD

**Issue by prolen** [dbcli/pgcli#870] opened 2018-05-08 06:33 UTC
can't create a connection with the recommend command
pgcli postgres://dbabc:pwd@8.8.2.12:5432/postgres
the error is:
authentication method 10 not supported

pgcli -h 8.8.2.12 -p 5432
authentication method 12 not supported

**Comment by fpietka** [comment] 2018-05-08 13:25
Hi @prolen 
Which version of pgcli are you using?
Can you provide the output of `pip list`?

**Comment by j-bennet** [comment] 2018-07-24 04:54
This seems to have been an issue in `psycopg2` built with older `libpq` 9 for PostgreSQL 10:

https://github.com/psycopg/psycopg2/issues/601

The issue is now fixed in psycopg2, so I'm going to close it here, but feel free to reopen if you're still having problems.

**Closed by j-bennet** 2018-07-24 04:54 UTC
