### ISSUE TITLE
Display bouncing when I hit enter

### ISSUE THREAD

**Issue by hakib** [dbcli/pgcli#418] opened 2015-11-21 07:41 UTC
Here is an example of how it looks like. This happens both on windows 7 and ubuntu.

![pgcli](https://cloud.githubusercontent.com/assets/6884290/11317327/dc685c4a-9033-11e5-8864-c0706952c5c7.gif)

**Comment by amjith** [comment] 2015-11-21 18:11
That looks quite bad. I'm not sure what's causing this flicker. 

Can you run `pip freeze`, so I can check the versions of the various packages? 

I'm particularly interested to know what version of prompt_toolkit you're using. This seems like a potential problem with [prompt_toolkit](https://github.com/jonathanslenders/python-prompt-toolkit).

**Comment by hakib** [comment] 2015-11-22 07:11
The version of `prompt_toolkit` is as required in setup.py.
```
λ python --version
Python 3.4.3

λ pip freeze
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
click==5.1
configobj==5.0.6
pgcli==0.20.1
pgspecial==1.2.0
prompt-toolkit==0.46
psycopg2==2.6.1
Pygments==2.0.2
six==1.10.0
sqlparse==0.1.16
wcwidth==0.1.5
```

I tried upgrading `prompt_toolkit` to the latest version

```
λ pip install --upgrade prompt-toolkit
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting prompt-toolkit from https://pypi.python.org/packages/3.4/p/prompt_toolkit/prompt_toolkit-0.54-py3-none-any.whl#md5=d48d7c4c6d04922b4fc94874a1a9fe97
  Downloading prompt_toolkit-0.54-py3-none-any.whl (194kB)
    100% |################################| 196kB 682kB/s
Requirement already up-to-date: six>=1.9.0 in c:\python34\lib\site-packages (from prompt-toolkit)
Requirement already up-to-date: wcwidth in c:\python34\lib\site-packages (from prompt-toolkit)
Requirement already up-to-date: pygments in c:\python34\lib\site-packages (from prompt-toolkit)
Installing collected packages: prompt-toolkit
  Found existing installation: prompt-toolkit 0.46
    Uninstalling prompt-toolkit-0.46:
      Successfully uninstalled prompt-toolkit-0.46

Successfully installed prompt-toolkit-0.54

λ pgcli
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 612, in _build_master
    ws.require(__requires__)
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 918, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 810, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 0.54 (c:\python34\lib\site-packages), Requirement.parse('prompt-toolkit==0.46'), {'pgcli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\pgcli-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 3018, in <module>
    working_set = WorkingSet._build_master()
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 614, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 627, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: prompt-toolkit==0.46
```

**Comment by amjith** [comment] 2015-11-22 08:54
@j-bennet This looks very similar to the issue you first had with wharfee. Do you have any insight on how this got fixed for you? 

@hakib Upgrading prompt_toolkit to the latest version won't work. I wouldn't do that. Are you seeing the same flicker in both Windows and Linux? Are they on different computers or is it on the same machine but on dual boot?

**Comment by hakib** [comment] 2015-11-22 09:09
>  Are they on different computers or is it on the same machine but on dual boot?

Same computer. Windows host with Ubuntu guest. I actually tried installing `pgcli` on my laptop to see if it's happening there too but `pip install pgcli` completed the installation but `pgcli` did not work afterwards. I haven't had time to check it out yet. Maybe I need to execute it directly from the `venv/bin` or something ...

**Comment by amjith** [comment] 2015-11-22 12:16
> pip install pgcli completed the installation but pgcli did not work afterwards.

If you installed it inside a virtualenv then you need to activate the virtualenv before you can execute pgcli.

> Same computer. Windows host with Ubuntu guest.

I'm wondering if this is a video card issue. I guess we'll find out once you try it on your laptop.

**Comment by hakib** [comment] 2015-11-26 14:03
Hey @amjith, just tested it on my laptop with a fresh installation of pgcli on a blank venv - **same problem**.

```
haki:~/src/testpgcli$ pyvenv venv
haki:~/src/testpgcli$ activate
(venv) haki:~/src/testpgcli$ python --version
Python 3.4.3+
(venv) haki:~/src/testpgcli$ pip install pgcli
Downloading/unpacking pgcli
  Downloading pgcli-0.20.1.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip-build-y5dwe2u1/pgcli/setup.py) egg_info for package pgcli
  
...

(venv) haki:~/src/testpgcli$ pip freeze
Pygments==2.0.2
click==6.0
configobj==5.0.6
pgcli==0.20.1
pgspecial==1.2.0
prompt-toolkit==0.46
psycopg2==2.6.1
setproctitle==1.1.9
six==1.10.0
sqlparse==0.1.16
wcwidth==0.1.5
```

This is on a lenovo ideapad laptop.

**Comment by amjith** [comment] 2015-11-30 13:43
Thanks for testing it on a different computer and reporting back. Sorry I haven't replied in a while, I was traveling and couldn't get reliable internet connection. 

I noticed that you've tested this exclusively on Python 3.4. I tried that on my laptop and I still don't see the flicker, but I'm on OS X. 

Can you try it on Python 2.7 to see if this still persists? 

@jonathanslenders Do you have any idea what could be happening? The gif posted in the first comment shows a flickering whenever the enter key is pressed. I'm not able to reproduce it, but I'm wondering if you've seen this or heard this behavior from someone else.

**Comment by hakib** [comment] 2015-11-30 15:16
@amjith, Same issue on python 2.7. It's pretty weird that on both my computers from different vendors with different OS's and different versions of python I get this flickering. Maybe there is some configuration i can try?

![pgcli](https://cloud.githubusercontent.com/assets/6884290/11475362/c44aedfe-9785-11e5-8fea-ca3d13d1adf5.gif)

**Comment by jonathanslenders** [comment] 2015-11-30 15:20
I don't understand how this is possible on Windows. For vt100 terminals (Mac/Linux), we have to wait for the CPR reponse (Cursor Position Request response). This one returns the x/y coordinates of the cursor position through stdin. As long as this has not been received, we don't know the space below the cursor and the bottom toolbar will not be displayed. For windows, we will always know the height, because that's a win32 call.

I will try to have a look next week. (Currently, I'm abroad for work.)

**Comment by jonathanslenders** [comment] 2015-11-30 15:21
Oh, btw, for Windows, I highly recommend to use conemu or cmder. (The Windows console is broken in many ways.)

**Comment by hakib** [comment] 2015-11-30 15:28
@jonathanslenders, the first example is cmder. The second is cmd. Both give the same flickering effect on both py2 & 3.4.

**Comment by jerome-peng** [comment] 2016-09-26 07:36
i have the same problem.
i use pgcli in redhat operate system.

$ pip freeze
click==6.6
configobj==5.0.6
humanize==0.5.1
mycli==1.8.0
pgcli==1.2.0
pgspecial==1.6.0
prompt-toolkit==1.0.3
psycopg2==2.6.2
pycrypto==2.6.1
Pygments==2.1.3
PyMySQL==0.7.9
setproctitle==1.1.10
six==1.10.0
sqlparse==0.2.0
wcwidth==0.1.7

it always flicker.

**Comment by amjith** [comment] 2016-10-04 03:49
@jerome-peng I've tried this on different computers and different OSes. But I still reproduce it. I suspect it is a combination of a graphics card and driver. This is so far beyond my understanding of the stack that I have no good solution for you. 😞 

All I can say is, did you try a different terminal? Say KTerm or gnome-terminal or xterm or urxvt?

**Comment by thurt** [comment] 2018-01-26 23:59
i have noticed similar flickering on mycli. 

i am using it in a docker container, perhaps that is the cause? https://hub.docker.com/r/jdecool/mycli/
or, i am also using a fairly barebones terminal, sakura, perhaps that is the problem. https://launchpad.net/sakura

**Comment by j-bennet** [comment] 2019-05-05 15:09
I don't think we can do much about this one, unfortunately. Closing.

**Closed by j-bennet** 2019-05-05 15:09 UTC
