### ISSUE TITLE
Text field with line returns not formatted properly

### ISSUE THREAD

**Issue by Graham42** [dbcli/pgcli#218] opened 2015-04-20 18:37 UTC
There's some data that has YAML in a text field. When selected it is not formatted properly because of the line returns in the YAML

Actual output
```
+-----------------+---------------------+----------------------------------+
|       some_id   |      some_other_id  | my_text_field                    |
|-----------------+---------------------+----------------------------------|
| XX-999999       |                   1 | --- 
STUFF_ID: AB_1111
THINGS: BLAH_VALUE |
```

The output I would expect should be something like this. The challenge would be differentiating between a record with multiple lines, and multiple records where some fields are null.
```
+-----------------+---------------------+----------------------------------+
|       some_id   |      some_other_id  | my_text_field                    |
|-----------------+---------------------+----------------------------------|
| XX-999999       |                   1 | ---                              |
|                 |                     | STUFF_ID: AB_1111                |
|                 |                     | THINGS: BLAH_VALUE               |
```

**Comment by amjith** [comment] 2015-04-20 19:02
Yes, multi-line output is handled poorly by the tabulate library. It might be time to rewrite tabulate to something more relevant to pgcli. :(

**Comment by amjith** [comment] 2015-05-26 17:39
This is a duplicate of #96.

**Closed by amjith** 2015-05-26 17:39 UTC
Labels: duplicate
