### ISSUE TITLE
Per-database prompt colours

### ISSUE THREAD

**Issue by Smylers** [dbcli/pgcli#1464] opened 2024-05-10 10:42 UTC
## Description

When switching between multiple similar databases, it would be useful to have different colours (“colors”) for instantly distinguishing between them.

For instance, displaying the prompt in a different colour based on the database name, with the config file specifying which foreground/background colour to use for which database name.

## Your environment

- [X] Ubuntu 22.04
- [X] 3.5.0
- [ ] What is the output of ``pip freeze`` command. [I don't think this is relevant for a feature request.]

**Comment by dbaty** [comment] 2024-05-10 11:24
This is a duplicate of #1249. Feel free to comment on that other issue or even contribute a pull request. :)

**Closed by dbaty** 2024-05-10 11:24 UTC
