### ISSUE TITLE
When will the pgcli tool be integrated into the postgresql trunk

### ISSUE THREAD

**Issue by xiaohuazi123** [dbcli/pgcli#1174] opened 2020-04-26 02:33 UTC
## Description

I want the author to merge this pgcli tool into the postgresql trunk
## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [x] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment] 2020-04-26 05:01
Hi @xiaohuazi123 - that's an interesting question! Nobody from postgres contacted us to express interest in making pgcli part of their repo. If that happens, we'd certainly consider it.

**Comment by xiaohuazi123** [comment] 2020-04-26 11:03
> Hi @xiaohuazi123 - that's an interesting question! Nobody from postgres contacted us to express interest in making pgcli part of their repo. If that happens, we'd certainly consider it.


Thank you for your reply. I think we can contact them and ask if they are interest in  making pgcli part of their repo.
This tool is so good, it's 100 times better than the official PSQL client tool.

**Comment by j-bennet** [comment] 2020-04-26 21:31
I'm happy that pgcli works for you (and a lot of other users). But it has its weak points, and in some areas it still wouldn't be able to replace the official client (you can find issues in our repo where we recommend people to use psql for their use cases that pgcli didn't handle well, such as non-interactive usage, or dumping data).

I'm going to close the issue, since it's not a bug.

Thank you for the suggestion!

**Closed by j-bennet** 2020-04-26 21:31 UTC
