### ISSUE TITLE
KeyError in thread completion_refresh

### ISSUE THREAD

**Issue by tejasmanohar** [dbcli/pgcli#675] opened 2017-03-21 23:06 UTC
## Description
I get this error occasionally here and there. I ^C and things work again.
```
Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/usr/local/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 105, in refresh_tables
    completer.extend_columns(executor.table_columns(), kind='tables')
  File "/usr/local/lib/python2.7/site-packages/pgcli/pgcompleter.py", line 158, in extend_columns
    metadata[schema][relname][colname] = column
KeyError: u'_stmp_3fc53b90_a'
```

## Your environment

- [x] Please provide your OS and version information.
I see it on ubuntu test server and os x machine when connecting to different databases so I think this is irrelevant
-  pgcli -v
Version: 1.3.1
- `pip freeze`
https://gist.github.com/tejasmanohar/ba53787fa736c95e6e867833e08db804

**Comment by j-bennet** [comment] 2017-03-26 21:24
Hi @tejasmanohar , thanks for the problem report. Is there anything specific to your workflow when this exception happens
 (making a lot of schema changes for example)? Are you working with the local or remote server?

**Comment by tejasmanohar** [comment] 2017-03-26 21:42
it's often the first query-- not making a lot of schema changes. remote server

**Comment by kennethkalmer** [comment] 2019-06-19 16:23
I just encountered a very similar issue after adding foreign keys to a partitioned table. Without the foreign keys partitioned tables work like a charm in pgcli. Turns out it can be reproduced quite easily:

```
$ createdb dev
$ pgcli dev
Server: PostgreSQL 11.3
Version: 2.1.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
kenneth@/tmp:dev> create table cities (id serial primary key not null, "name" text);
CREATE TABLE
Time: 0.009s
kenneth@/tmp:dev> CREATE TABLE measurement (
     city_id         bigint references cities (id),
     logdate         date not null,
     peaktemp        int,
     unitsales       int
 ) PARTITION BY RANGE (logdate);
CREATE TABLE
Time: 0.006s
kenneth@/tmp:dev> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in runompletions...
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/pgcli/2.1.1/libexec/lib/python3.7/site-packages/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/usr/local/Cellar/pgcli/2.1.1/libexec/lib/python3.7/site-packages/pgcli/completion_refresher.py", line 110, in refresh_tables
    completer.extend_foreignkeys(executor.foreignkeys())
  File "/usr/local/Cellar/pgcli/2.1.1/libexec/lib/python3.7/site-packages/pgcli/pgcompleter.py", line 278, in extend_foreignkeys
    childcolmeta = meta[childschema][childtable][childcol]
KeyError: 'measurement'

kenneth@/tmp:dev> \d measurement;
+-----------+---------+-------------+
| Column    | Type    | Modifiers   |
|-----------+---------+-------------|
| city_id   | bigint  |             |
| logdate   | date    |  not null   |
| peaktemp  | integer |             |
| unitsales | integer |             |
+-----------+---------+-------------+
Partition key: RANGE (logdate)

Time: 0.024s
```

Note the output doesn't show the foreign key, where `psql` displays it:

```
$ ~ psql dev
psql (11.3)
Type "help" for help.

dev=# \d measurement
              Table "public.measurement"
  Column   |  Type   | Collation | Nullable | Default
-----------+---------+-----------+----------+---------
 city_id   | bigint  |           |          |
 logdate   | date    |           | not null |
 peaktemp  | integer |           |          |
 unitsales | integer |           |          |
Partition key: RANGE (logdate)
Foreign-key constraints:
    "measurement_city_id_fkey" FOREIGN KEY (city_id) REFERENCES cities(id)
Number of partitions: 0
```

**Comment by madeindjs** [comment] 2021-02-17 08:17
Same error on version 1.9.1 with a partitioned table:

~~~
Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in runs-mode     Refreshing 
    self._target(*self._args, **self._kwargs)
  File "/usr/share/pgcli/pgcli/completion_refresher.py", line 68, in _bg_refresh
    refresher(completer, executor)
  File "/usr/share/pgcli/pgcli/completion_refresher.py", line 111, in refresh_tables
    completer.extend_foreignkeys(executor.foreignkeys())
  File "/usr/share/pgcli/pgcli/pgcompleter.py", line 265, in extend_foreignkeys
    childcolmeta =  meta[childschema][childtable][childcol]
KeyError: 'daily_query'
~~~

Also I have same error than @kennethkalmer , foreign key and partition not appear with `\d`

* pgcli

~~~sql
database> \d+ daily_query
+-------------+---------+-----------+
| Column      | Type    | Storage   |
|-------------+---------+-----------|
| id          | integer | plain     |
| relatedDate | date    | plain     |
| clicks      | integer | plain     |
| impressions | integer | plain     |
| queryId     | integer | plain     |
| ctr         | numeric | main      |
| position    | numeric | main      |
| siteId      | integer | plain     |
| inaccurate  | boolean | plain     |
+-------------+---------+-----------+
Time: 0.009s
~~~

* psql

~~~sql
database=# \d+ daily_query
                                                        Table "public.daily_query"
   Column    |  Type   | Collation | Nullable |                       Default                       | Storage | Stats target | Description 
-------------+---------+-----------+----------+-----------------------------------------------------+---------+--------------+-------------
 id          | integer |           | not null | nextval('daily_query_partitioned_id_seq'::regclass) | plain   |              | 
 relatedDate | date    |           | not null |                                                     | plain   |              | 
 clicks      | integer |           | not null |                                                     | plain   |              | 
 impressions | integer |           | not null |                                                     | plain   |              | 
 queryId     | integer |           |          |                                                     | plain   |              | 
 ctr         | numeric |           | not null |                                                     | main    |              | 
 position    | numeric |           | not null |                                                     | main    |              | 
 siteId      | integer |           | not null |                                                     | plain   |              | 
 inaccurate  | boolean |           | not null | false                                               | plain   |              | 
Partition key: LIST ("siteId")
Indexes:
    "daily_query_partitioned_pkey" PRIMARY KEY, btree (id, "siteId")
    "UQ_96353c541bcfa0cac190f73ddee" UNIQUE CONSTRAINT, btree ("queryId", "relatedDate", "siteId")
    "IDX_1c84dca3b0c1fe63e769021b1d" btree ("queryId")
    "IDX_3da070500e160586963844c163" btree ("siteId")
    "daily_query_relateddate_brin_index" brin ("relatedDate") WITH (pages_per_range='32', autosummarize=off)
Foreign-key constraints:
    "FK_1c84dca3b0c1fe63e769021b1d4" FOREIGN KEY ("queryId") REFERENCES query(id)
    "FK_3da070500e160586963844c1638" FOREIGN KEY ("siteId") REFERENCES site(id)
Partitions: daily_query_site_101 FOR VALUES IN (101),
            daily_query_site_12 FOR VALUES IN (12),
            daily_query_site_13 FOR VALUES IN (13),
~~~

**Comment by msva** [comment] 2021-03-01 12:10
I'm also getting that on pgcli-2.1.1-py3-none-any.whl

I'd prefer to not share table strucrure if it is not necessarily, but backtrace is identical to @madeindjs 's one

**Comment by ivorscott** [comment] 2021-07-06 20:04
Same issue. It doesn't appear to affect my development work but its unexpected behavior.

<img width="961" alt="Screen Shot 2021-07-06 at 22 02 44" src="https://user-images.githubusercontent.com/1488558/124660040-f5d0bd00-dea5-11eb-866a-51e6782b68ea.png">

### How to reproduce
```
version: '3.1'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-net

  debug-db:
    image: dencold/pgcli
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    networks:
      - postgres-net

networks:
  postgres-net:

volumes:
  psql-data:
```

docker-compose up -d db
docker-compose run debug-db

**Comment by j-bennet** [comment] 2021-07-07 16:59
This version of pgcli (1.10.3) is very old. Issue was fixed in 3.0.0, in https://github.com/dbcli/pgcli/pull/1145. Lates released pgcli version is 3.1.0, I'd recommend updating to that.

**Closed by j-bennet** 2021-07-07 16:59 UTC

**Comment by gojanpaolo** [comment] 2021-12-17 00:48
I get a similar error on pgcli 3.2.0
```
Server: PostgreSQL 13.4
Version: 3.2.0
Home: http://pgcli.com
postgres> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 910, in runmacs-mode     Refreshing completions...                                                                   
    self._target(*self._args, **self._kwargs)
  File "C:\Python39\lib\site-packages\pgcli\completion_refresher.py", line 61, in _bg_refresh
    executor = pgexecute.copy()
  File "C:\Python39\lib\site-packages\pgcli\pgexecute.py", line 270, in copy
    return self.__class__(**self._conn_params)
  File "C:\Python39\lib\site-packages\pgcli\pgexecute.py", line 260, in __init__
    self.connect(database, user, password, host, port, dsn, **kwargs)
  File "C:\Python39\lib\site-packages\pgcli\pgexecute.py", line 306, in connect
    conn = psycopg2.connect(**conn_params)
  File "C:\Python39\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.InterfaceError: only protocol 3 supported
```

**Comment by j-bennet** [comment] 2022-02-21 23:22
@gojanpaolo The issue you're seeing is not the same.

`psycopg2.InterfaceError: only protocol 3 supported` is most likely caused by using an old version of PostgreSQL.

If you're still experiencing this, please open an issue and provide your system information (OS version, PostgreSQL version, pgcli version).

**Comment by hui-zheng** [comment] 2023-07-24 21:06
I also encounter this when using pgcli  with [Materialize](https://materialize.com/), a realtime analytic data engine that is wire-compatible with PostgreSQL.

a work-around seems to be turning off `SMART COMPLETION` in pgcli.
