### ISSUE TITLE
Loading a db dump fails

### ISSUE THREAD

**Issue by dideler** [dbcli/pgcli#990] opened 2019-01-16 11:58 UTC
## Description

Given a database dump, in a `structure.sql` file for example, `pgcli` is unable to load the dump.

### Expected

Similar to `psql DB_NAME < structure.sql`, expected `pgcli DB_NAME < structure.sql` to work.

### Actual

```
$ pgcli example-db < ./db/structure.sql
Warning: Input is not to a terminal (fd=0).
Server: PostgreSQL 10.6
Version: 2.0.2
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
example-db> --
can't execute an empty query
Time: 0.002s
example-db> -- PostgreSQL database dump
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.001s
example-db>

Time: 0.000s
example-db> -- Dumped from database version 9.6.8
can't execute an empty query
Time: 0.000s
example-db> -- Dumped by pg_dump version 9.6.8
can't execute an empty query
Time: 0.000s
example-db>

Time: 0.000s
example-db> SET statement_timeout = 0;
SET
Time: 0.003s
example-db> SET lock_timeout = 0;
SET
Time: 0.000s
example-db> SET idle_in_transaction_session_timeout = 0;
SET
Time: 0.000s
example-db> SET client_encoding = 'UTF8';
SET
Time: 0.000s
example-db> SET standard_conforming_strings = on;
SET
Time: 0.000s
example-db> SELECT pg_catalog.set_config('search_path', '', false);
+--------------+
| set_config   |
|--------------|
|              |
+--------------+
SELECT 1
Time: 0.014s
example-db> SET check_function_bodies = false;
SET
Time: 0.000s
example-db> SET client_min_messages = warning;
SET
Time: 0.000s
example-db> SET row_security = off;
SET
Time: 0.001s
example-db>

Time: 0.000s
example-db> --
can't execute an empty query
Time: 0.000s
example-db> -- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.000s
example-db>

Time: 0.000s
example-db> CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION
Time: 0.005s
example-db>

Time: 0.000s
example-db>

Time: 0.000s
example-db> --
can't execute an empty query
Time: 0.005s
example-db> -- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.001s
example-db>

Time: 0.000s
example-db> COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
COMMENT
Time: 0.011s
example-db>

Time: 0.000s
example-db>

Time: 0.000s
example-db> --
can't execute an empty query
Time: 0.000s
example-db> -- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.000s
example-db>

Time: 0.000s
example-db> CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION
Time: 0.026s
example-db>

Time: 0.000s
example-db>

Time: 0.000s
example-db> --
can't execute an empty query
Time: 0.001s
example-db> -- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.001s
example-db>

Time: 0.000s
example-db> COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';
COMMENT
Time: 0.002s
example-db>

Time: 0.000s
example-db>

Time: 0.000s
example-db> SET default_tablespace = '';
SET
Time: 0.002s
example-db>

Time: 0.000s
example-db> SET default_with_oids = false;
SET
Time: 0.000s
example-db>

Time: 0.000s
example-db> --
can't execute an empty query
Time: 0.001s
example-db> -- Name: background_logs; Type: TABLE; Schema: public; Owner: -
can't execute an empty query
Time: 0.001s
example-db> --
can't execute an empty query
Time: 0.001s
example-db>

Time: 0.000s
example-db> CREATE TABLE public.background_logs (
syntax error at end of input
LINE 1: CREATE TABLE public.background_logs (
                                             ^

Time: 0.001s
example-db>     id integer NOT NULL,
syntax error at or near "id"
LINE 1: id integer NOT NULL,
        ^

Time: 0.001s
example-db>     job character varying,
syntax error at or near "job"
LINE 1: job character varying,
        ^

Time: 0.001s
example-db>     category character varying,
syntax error at or near "category"
LINE 1: category character varying,
        ^

Time: 0.001s
example-db>     finished_at timestamp without time zone,
syntax error at or near "finished_at"
LINE 1: finished_at timestamp without time zone,
        ^

Time: 0.001s
example-db>     created_at timestamp without time zone NOT NULL,
syntax error at or near "created_at"
LINE 1: created_at timestamp without time zone NOT NULL,
        ^

Time: 0.001s
example-db>     updated_at timestamp without time zone NOT NULL
syntax error at or near "updated_at"
LINE 1: updated_at timestamp without time zone NOT NULL
        ^

Time: 0.001s
example-db> );
syntax error at or near ")"
LINE 1: )
        ^
```
and so on for the rest of interpreting the dump file.

## Environment

- [x] Please provide your OS and version information.
  - macOS 10.14.2
- [x] Please provide your CLI version.
  - pgcli 2.0.2, psql (PostgreSQL) 11.1
- [x] What is the output of ``pip freeze`` command.
```
aniso8601==3.0.2
astroid==2.0.2
autopep8==1.3.5
botocore==1.12.38
certifi==2018.4.16
click==6.7
docutils==0.14
Flask==0.12.2
Flask-RESTful==0.3.6
isort==4.3.4
itsdangerous==0.24
Jinja2==2.10
jmespath==0.9.3
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
pipenv==2018.11.26
prettytable==0.7.2
pycodestyle==2.4.0
pylint==2.1.0
python-dateutil==2.7.5
pytz==2018.5
s3transfer==0.1.13
six==1.11.0
typed-ast==1.1.0
typing==3.6.4
urllib3==1.24.1
virtualenv==16.2.0
virtualenv-clone==0.3.0
Werkzeug==0.14.1
wrapt==1.10.11
```

**Comment by j-bennet** [comment] 2019-05-05 03:19
`pgcli` was built for interactive use. It is best to still use `psql` for non-interactive tasks, like data export or import. I'm not saying this is impossible to implement, but our primary focus was not on this functionality. If someone decides to add it, we'd welcome the PR!

**Comment by j-bennet** [comment] 2019-05-05 14:58
Duplicate of https://github.com/dbcli/pgcli/issues/307.

**Closed by j-bennet** 2019-05-05 14:58 UTC
Labels: help wanted
