### ISSUE TITLE
Messages in real time

### ISSUE THREAD

**Issue by LionelR** [dbcli/pgcli#637] opened 2017-02-02 15:37 UTC
pgcli doesn't report server messages synchronously, and report all of them in one pass which can be not relevant when we need to follow a function execution with many RAISE statements.
As an example 
```
CREATE FUNCTION public.test() RETURNS VOID AS $$
BEGIN
	RAISE INFO 'Current timestamp: %', timeofday()::TIMESTAMP;
	PERFORM pg_sleep(1);
  RAISE INFO 'Current timestamp: %', timeofday()::TIMESTAMP;
	PERFORM pg_sleep(1);
  RAISE INFO 'Current timestamp: %', timeofday()::TIMESTAMP;
	PERFORM pg_sleep(1);
END;
$$ LANGUAGE 'plpgsql' STRICT;
```
In psql, the messages of this function will be displayed as they come, but not in pgcli.

**Comment by amjith** [comment] 2017-02-10 04:43
You're right. This is a shortcoming of pgcli. The library used by pgcli to fetch the messages from Postgres doesn't happen synchronously. It happens after the query has finished execution. 

I'm not sure if there is a better way to implement this. 😞

**Comment by koljonen** [comment] 2017-03-05 00:16
Closing as a duplicate of #430. I definitely agree it would be nice if we could do something about this, though.

**Closed by koljonen** 2017-03-05 00:16 UTC
