### ISSUE TITLE
EDITOR variable not respected while invoked dynamically

### ISSUE THREAD

**Issue by gdevanla** [dbcli/pgcli#1235] opened 2021-01-09 16:45 UTC
## Description

Thanks for the awesome library! I would like to suggest one other improvement.

I use Emacs as my default editor and I have a emacs daemon running on the background. I connect to the emacs daemon with a alias command say `ecr` that starts the emacsclient.  I would like to use the same client while editing sql from inside pgcli.  

To make this work, I tried this:

EDITOR=ecr pgcli ...

But, when I invoke the editor using \e, the alias command set with EDITOR is not being used.

## Your environment

- [ ] Please provide your OS and version information.
Linux
- [ ] Please provide your CLI version.
Server: PostgreSQL 12.3                                                                                                                                                                                             
Version: 2.2.0      
- [ ] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment] 2021-01-18 22:18
A few questions:

1. What happens if you provide a non-existing editor: `EDITOR=foo pgcli` and try to invoke `\e` from pgcli? Expected behavior would be an error like this:

```
$ EDITOR=foo pgcli test
Server: PostgreSQL 13.1
Version: 3.1.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
test> select 1 \e
/bin/sh: foo: command not found
Error: foo: Editing failed!
```

2. What editor is invoked when you run pgcli with `EDITOR=xxx` and use `\e`?
3. What is your installed version of `click` and `pgspecial`? (`pip freeze`) and are you able to upgrade pgcli? It's been a while since 2.2.0.

**Comment by gdevanla** [comment] 2021-01-19 06:48
Interesting. I do not see any errors. It always invokes the `emacs -nw` which is the value of EDITOR I get when I print it using `echo`. Same behaviour when I use `foo` or `ecr`. 

I tried this on latest master: And here is the output of `pip freeze`

attrs==20.3.0
backcall==0.2.0
cli-helpers==2.1.0
click==7.1.2
configobj==5.0.6
decorator==4.4.2
iniconfig==1.1.1
ipdb==0.13.4
ipython==7.19.0
ipython-genutils==0.2.0
jedi==0.18.0
mock==4.0.3
packaging==20.8
parso==0.8.1
pendulum==2.1.2
pexpect==4.8.0
-e git+https://github.com/gdevanla/pgcli.git@baea7690b0e64cf2487a5ebcc61ca2e6736caf05#egg=pgcli
pgspecial==1.11.10
pickleshare==0.7.5
pluggy==0.13.1
prompt-toolkit==3.0.8
psycopg2==2.8.6
ptyprocess==0.7.0
py==1.10.0
Pygments==2.7.3
pyparsing==2.4.7
pytest==6.2.1
python-dateutil==2.8.1
pytzdata==2020.1
setproctitle==1.2.1
six==1.15.0
sqlparse==0.4.1
tabulate==0.8.7
terminaltables==3.1.0
toml==0.10.2
traitlets==5.0.5
UNKNOWN==0.0.0
wcwidth==0.2.5

**Comment by j-bennet** [comment] 2021-01-19 18:05
Are you using `fish` shell by any chance? From what I remember, in earlier version of `fish` `ENV_VAR=value command` syntax was not supported.

**Comment by gdevanla** [comment] 2021-01-23 18:33
Sorry for the delayed response.  I am using `zsh`, but I also tried just using `bash`, to make sure if was not the shell. I found the same issue, though.  I am on Ubuntu 18.

**Comment by gdevanla** [comment] 2021-01-30 16:23
I dug through this a litter deeper and this is what I found.  In `pgspecial` , `iocommands.py` module, we call into `click.edit(..)`.

Eventually, `click`, while trying to instantiate the `Editor` object, uses this loop to pick the editor.

```
  for key in "VISUAL", "EDITOR":                                                                                                                                                                              
            rv = os.environ.get(key)                                                                                                                                                                                
            if rv:                                                                                                                                                                                                  
                return rv 
```

In my case, the VISUAL was still set to the old editor and click was picking up the setting of `VISUAL` rather than `EDITOR`.

Perhaps, we should update our documentation to reflect this?

**Comment by j-bennet** [comment] 2021-01-30 20:59
Wow, nice debugging. Yes, updating the docs is a good idea. I never even knew about the `VISUAL` env var.

**Comment by j-bennet** [comment] 2021-01-30 21:47
Added documentation about VISUAL eenv var on editor page (https://www.pgcli.com/editor):

https://github.com/dbcli/pgcli.com/pull/45

Closing the issue. Great work @gdevanla. 🌟

**Closed by j-bennet** 2021-01-30 21:47 UTC
