### ISSUE TITLE
Error connecting to PostgreSQL 12beta1

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#1058] opened 2019-05-24 15:03 UTC
## Description
Error connecting to PostgreSQL 12beta1
```
Server: PostgreSQL 12beta1,
Version: 2.1.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres@windows-db:/postgres dbcli>
  File "c:\data\flash drive\portableapps\python\lib\threading.py", line 917, in _bootstrap_inner
                                         self.run()
  File "c:\data\flash drive\portableapps\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\data\flash drive\portableapps\python\lib\site-packages\pgcli\completion_refresher.py", line 64, in _bg_refresh
    refresher(completer, executor)
  File "c:\data\flash drive\portableapps\python\lib\site-packages\pgcli\completion_refresher.py", line 106, in refresh_tables
    completer.extend_columns(executor.table_columns(), kind='tables')
  File "c:\data\flash drive\portableapps\python\lib\site-packages\pgcli\pgcompleter.py", line 203, in extend_columns
    for schema, relname, colname, datatype, has_default, default in column_data:
  File "c:\data\flash drive\portableapps\python\lib\site-packages\pgcli\pgexecute.py", line 568, in table_columns
    for row in self._columns(kinds=['r']):
  File "c:\data\flash drive\portableapps\python\lib\site-packages\pgcli\pgexecute.py", line 563, in _columns
    cur.execute(sql)
psycopg2.errors.UndefinedColumn: column def.adsrc does not exist
LINE 7:                         def.adsrc as default
                                ^
```
## Your environment

- [x] Please provide your OS and version information: Windows  10
- [x] Please provide your CLI version: 2.1.0
- [ ] What is the output of ``pip freeze`` command.

**Comment by thorstenkampe** [comment] 2019-05-24 16:01
Background: `The adsrc field is historical, and is best not used, because it does not track outside changes that might affect the representation of the default value. Reverse-compiling the adbin field (with pg_get_expr for example) is a better way to display the default value.` (https://www.postgresql.org/docs/current/catalog-pg-attrdef.html). In PostgreSQL 12 it has been dropped: https://www.postgresql.org/docs/12/catalog-pg-attrdef.html

**Comment by boerwastaken** [comment] 2019-06-03 09:57
Here's two hacks to get it going again, quite likely not the correct solution:

[diff for pgcli](https://github.com/dbcli/pgcli/compare/master...boerwastaken:postgresql-12)

[diff for pgspecial](https://github.com/dbcli/pgspecial/compare/master...boerwastaken:postgresql-12)

**Comment by j-bennet** [comment] 2019-06-03 22:14
@boerwastaken The diffs seem reasonable, why do you think it's not the correct solution?

**Comment by thorstenkampe** [comment] 2019-06-04 01:49
1. the warning against using `adsrc` is in the documentation  since PostgreSQL 8.0 (2005). It should have never been used
2. that means the solution should not be applied to PostgreSQL 12 exclusively but to all versions greater than 7.
3. the documentation recommends replacing `def.adsrc` with `pg_get_expr(def.adbin)`
4. pgspecial does not query `def.adsrc` so I can't see any need to patch pgspecial

**Comment by boerwastaken** [comment] 2019-06-04 02:01
> The diffs seem reasonable, why do you think it's not the correct solution?

@j-bennet i'll walk through it:

1. [here](https://github.com/dbcli/pgspecial/compare/master...boerwastaken:postgresql-12#diff-b4b65e8639b6f8f4d48ce903a6f0002dR731) `true` is just made up, I don't fully understand the OID situation and in particular how pgcli interacts with it

2. [here](https://github.com/dbcli/pgcli/compare/master...boerwastaken:postgresql-12#diff-36fcb873925169e72e8c5ca4e8a8a581R229) I suspect that those missing dictionary entries are supposed to be created elsewhere, as this used to work before without this, and I don't know if some other setup is done related to those entries.

So all in all, I think it's a hack that shows some of the areas for which pgcli needs adaptations for postgresql-12. Also for some reason if I apply this patch to

**Comment by alivesree** [comment] 2019-10-15 05:27
Replace "d.adsrc" by "pg_get_expr(d.adbin, d.adrelid) AS default" in the query written in  adminer.php file.
If the problem is while connecting pgsql via adminer.php

**Comment by alivesree** [comment] 2019-10-15 05:29
**Replace "d.adsrc" by "pg_get_expr(d.adbin, d.adrelid) AS default"** in the query written in adminer.php file.
If the problem is while connecting pgsql via adminer.php

**Comment by Globegitter** [comment] 2019-10-22 08:30
Any chance of releasing a new version with a fix, since psql 12 is out now?

**Comment by shilov** [comment] 2019-10-24 05:48
Bumped into this as well.

**Comment by amjith** [comment] 2019-10-24 06:42
I'll see if I can do a release this weekend. In the meantime you can install from master directly using this command: 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by muusik** [comment] 2019-11-20 16:17
Somewhat related, in that @boerwastaken 's patch looks like it would fix it -- \d fails: 
```
Server: PostgreSQL 12.1 (Debian 12.1-1)
Version: 2.1.1
...
\d customer                                                                                                                                                                                         
column c.relhasoids does not exist
LINE 2: ...                 c.relhasrules, c.relhastriggers, c.relhasoi...
                                                             ^
```

**Comment by j-bennet** [comment] 2019-12-04 17:33
Fixed in 2.2.0.

**Closed by j-bennet** 2019-12-04 17:33 UTC

**Comment by goldo** [comment] 2019-12-05 17:50
thx @j-bennet ! Do you know when will it be available on brew ?

**Comment by amjith** [comment] 2019-12-05 19:17
@goldo We don't maintain the brew formula for pgcli. I believe there exists a bot that runs periodically and updates the formula. 

Here's the relevant formula if you're inclined to send them a PR. 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgcli.rb

**Comment by goldo** [comment] 2019-12-05 19:26
@amjith thanks for the explanation !
