### ISSUE TITLE
port shouldn't be required for DSN's in alias_dsn section

### ISSUE THREAD

**Issue by msztolcman** [dbcli/pgcli#657] opened 2017-03-08 06:27 UTC
Currently dsn in form:

    somename = postgresql://postgres:password@host/eden

is invalid, after running pgcli `pgcli -D somename` it prints:

    invalid port number: "None"

It should be required (wasn't in previous versions). I didn't verified other fields.

**Comment by j-bennet** [comment] 2017-03-08 06:56
Looks like this is also caused by latest psycopg2. See if this fixes it:

`pip install psycopg2==2.6.2`

**Comment by j-bennet** [comment] 2017-03-08 06:58
Aha. Found it. https://github.com/psycopg/psycopg2/issues/524

**Comment by msztolcman** [comment] 2017-03-08 08:00
Yep, after downgrading psycopg it's better now, thanks :)

**Comment by amjith** [comment] 2017-03-08 17:02
Sigh. We should fix this. ☹️

**Comment by j-bennet** [comment] 2017-05-28 22:29
Fixed in 1.5.1.

**Closed by j-bennet** 2017-05-28 22:29 UTC
